### ISSUE TITLE
Permission errors when installing as notebook user

### ISSUE THREAD

**Issue by onepan** [ideonate/cdsdashboards-jupyter-docker#2]
When using the containds-allr-datascience image as a base, installing libraries as the notebook user fails. 

It looks like the cause is in the datascience-notebook-all [Dockerfile](https://github.com/ideonate/cdsdashboards-jupyter-docker/blob/master/all/Dockerfile). Specifically, installing packages as root seems to block installing packages later as the notebook user. 

For example, using this Dockerfile as is works, but uncommenting the `USER root` line in `datascience-notebook-all` causes the final `conda install` to fail due to permissions.

```Dockerfile
# equivalent to ideonate/datascience-notebook-voila
FROM jupyter/datascience-notebook:latest AS datascience-notebook-voila

RUN rm -rf /home/jovyan/work

RUN conda install --quiet --yes -c conda-forge voila

RUN pip install jhsingle-native-proxy>=0.3.2 voila-materialstream>=0.2.6


USER $NB_UID
COPY cdsdashboards-jupyter-docker/voila/jupyter_notebook_config_extra.py /etc/jupyter/
RUN cat /etc/jupyter/jupyter_notebook_config_extra.py >> /etc/jupyter/jupyter_notebook_config.py
RUN rm /etc/jupyter/jupyter_notebook_config_extra.py

COPY cdsdashboards-jupyter-docker/voila/voila.json /etc/jupyter


# Fix permissions on /etc/jupyter as root
USER root
RUN fix-permissions /etc/jupyter/

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID



# equivalent to ideonate/datascience-notebook-all
FROM datascience-notebook-voila AS datascience-notebook-all

# CHANGE: use the notebook user instead of root
# USER root

RUN pip install streamlit

RUN pip install dash plotlydash-tornado-cmd>=0.0.4

RUN pip install bokeh panel bokeh-root-cmd>=0.0.5

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID



# Example customized Dockerfile
FROM datascience-notebook-all

RUN conda install --quiet --yes \
    'altair=4.1.*'
```

As far as I can see, there's no need to change to root when doing the `pip install` - maybe there's a downstream reason? The Jupyter images all install packages as nb user. Note that in the current state, installing packages as root **does** work. Still, might be worth matching the other images for consistency.

**Comment by danlester** [comment]
@onepan thank you very much for this report. I think you're right that we just don't want to run pip as root.

Would you be kind enough to try out the latest images which have been built under tag sha-d0967d7?

e.g. ideonate/containds-allr-datascience:sha-d0967d7

And then if things look OK I'll re-tag them as 0.1.0 to become the official images.

Thanks,

Dan

**Comment by onepan** [comment]
Tested it out and everything is working for me. Thanks!

**Comment by danlester** [comment]
Fantastic, thanks for letting me know. I have now tagged these images as 0.1.0.

Dan
